// <auto-generated />
using BookStore_CW;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStore_CW.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("BookStore_CW.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PictureURL")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearofPublish")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BookStore_CW.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("BookStore_CW.BookOnSale", b =>
                {
                    b.HasBaseType("BookStore_CW.Book");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalePercent")
                        .HasColumnType("INTEGER");

                    b.ToTable("BooksOnSale", (string)null);
                });

            modelBuilder.Entity("BookStore_CW.DefferedBooks", b =>
                {
                    b.HasBaseType("BookStore_CW.Book");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("UserId");

                    b.ToTable("DefferedBooks", (string)null);
                });

            modelBuilder.Entity("BookStore_CW.SoldBook", b =>
                {
                    b.HasBaseType("BookStore_CW.Book");

                    b.ToTable("SoldBooks", (string)null);
                });

            modelBuilder.Entity("BookStore_CW.BookOnSale", b =>
                {
                    b.HasOne("BookStore_CW.Book", null)
                        .WithOne()
                        .HasForeignKey("BookStore_CW.BookOnSale", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore_CW.DefferedBooks", b =>
                {
                    b.HasOne("BookStore_CW.Book", null)
                        .WithOne()
                        .HasForeignKey("BookStore_CW.DefferedBooks", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore_CW.User", "User")
                        .WithMany("DefferedBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookStore_CW.SoldBook", b =>
                {
                    b.HasOne("BookStore_CW.Book", null)
                        .WithOne()
                        .HasForeignKey("BookStore_CW.SoldBook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore_CW.User", b =>
                {
                    b.Navigation("DefferedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
